name: Build Docker Image
on:
  push:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        {%- raw %}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        {%- endraw %}
        repository: {{ cookiecutter.image_name }}
        tag_with_ref: true
        add_git_labels: true
        cache_froms: {{ cookiecutter.image_name }}:{%- raw %}${{ steps.extract_branch.outputs.branch }}{%- endraw %}, {{ cookiecutter.image_name }}:latest
        build_args: BUILDKIT_INLINE_CACHE=1,SERVO_ENV=development
