name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install and configure Poetry
      run: |
        pip install poetry==1.0.*
        poetry config virtualenvs.in-project true
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: .venv
        {%- raw %}
        key: venv-${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        {%- endraw %}
    - name: Install dependencies
      run: poetry install
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        {%- raw %}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        {%- endraw %}
        repository: {{ cookiecutter.image_name }}
        tag_with_ref: true
        add_git_labels: true
        cache_froms: {{ cookiecutter.image_name }},{{ cookiecutter.base_image }}
        build_args: BUILDKIT_INLINE_CACHE=1,SERVO_ENV=production
